onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /CPU_toplevel_tb/dut/clk
add wave -noupdate /CPU_toplevel_tb/dut/reset
add wave -noupdate /CPU_toplevel_tb/dut/instrAddress
add wave -noupdate /CPU_toplevel_tb/dut/PCPlus4
add wave -noupdate /CPU_toplevel_tb/dut/brAddress
add wave -noupdate /CPU_toplevel_tb/dut/brPlusPC
add wave -noupdate /CPU_toplevel_tb/dut/PCNext
add wave -noupdate /CPU_toplevel_tb/dut/CondAddr19
add wave -noupdate /CPU_toplevel_tb/dut/BrAddr26
add wave -noupdate /CPU_toplevel_tb/dut/instruction
add wave -noupdate /CPU_toplevel_tb/dut/Aw
add wave -noupdate /CPU_toplevel_tb/dut/Ab
add wave -noupdate /CPU_toplevel_tb/dut/Aa
add wave -noupdate /CPU_toplevel_tb/dut/AbFinal
add wave -noupdate /CPU_toplevel_tb/dut/shamt
add wave -noupdate /CPU_toplevel_tb/dut/Dw
add wave -noupdate /CPU_toplevel_tb/dut/Db
add wave -noupdate /CPU_toplevel_tb/dut/Da
add wave -noupdate /CPU_toplevel_tb/dut/result
add wave -noupdate /CPU_toplevel_tb/dut/mem_data
add wave -noupdate /CPU_toplevel_tb/dut/Imm64Bit
add wave -noupdate /CPU_toplevel_tb/dut/aluBIn
add wave -noupdate /CPU_toplevel_tb/dut/shiftResult
add wave -noupdate /CPU_toplevel_tb/dut/calculatedResult
add wave -noupdate /CPU_toplevel_tb/dut/Imm12
add wave -noupdate /CPU_toplevel_tb/dut/Imm9
add wave -noupdate /CPU_toplevel_tb/dut/aluFlagsIn
add wave -noupdate /CPU_toplevel_tb/dut/flags
add wave -noupdate /CPU_toplevel_tb/dut/invertedClock
add wave -noupdate /CPU_toplevel_tb/dut/zeroCBZ
add wave -noupdate /CPU_toplevel_tb/dut/AwPass
add wave -noupdate /CPU_toplevel_tb/dut/instrFetchtoDecodePipe
add wave -noupdate /CPU_toplevel_tb/dut/instrDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/instrExectoMemPipe
add wave -noupdate /CPU_toplevel_tb/dut/instrMemtoWrPipe
add wave -noupdate /CPU_toplevel_tb/dut/BDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/ADecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/ALUExectoMemPipe
add wave -noupdate /CPU_toplevel_tb/dut/writebackMemtoWrPipe
add wave -noupdate /CPU_toplevel_tb/dut/DbDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/DinExectoMemPipe
add wave -noupdate /CPU_toplevel_tb/dut/DaFinal
add wave -noupdate /CPU_toplevel_tb/dut/DbFinal
add wave -noupdate /CPU_toplevel_tb/dut/PCFetchtoDecodePipe
add wave -noupdate /CPU_toplevel_tb/dut/RegWriteDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/RegWriteExectoMemPipe
add wave -noupdate /CPU_toplevel_tb/dut/RegWriteMemtoWrPipe
add wave -noupdate /CPU_toplevel_tb/dut/setFlagsDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/MemWriteDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/MemWriteExectoMemPipe
add wave -noupdate /CPU_toplevel_tb/dut/MemtoRegDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/MemtoRegExectoMemPipe
add wave -noupdate /CPU_toplevel_tb/dut/shiftTrueDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/MemReadDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/MemReadExectoMemPipe
add wave -noupdate /CPU_toplevel_tb/dut/ALUOpDecodetoExecPipe
add wave -noupdate /CPU_toplevel_tb/dut/AForward
add wave -noupdate /CPU_toplevel_tb/dut/BForward
add wave -noupdate /CPU_toplevel_tb/dut/BrTaken
add wave -noupdate /CPU_toplevel_tb/dut/UnCondBr
add wave -noupdate /CPU_toplevel_tb/dut/RegWrite
add wave -noupdate /CPU_toplevel_tb/dut/setFlags
add wave -noupdate /CPU_toplevel_tb/dut/MemWrite
add wave -noupdate /CPU_toplevel_tb/dut/MemToReg
add wave -noupdate /CPU_toplevel_tb/dut/ALUSrc
add wave -noupdate /CPU_toplevel_tb/dut/ITypetoB
add wave -noupdate /CPU_toplevel_tb/dut/Reg2Loc
add wave -noupdate /CPU_toplevel_tb/dut/shiftTrue
add wave -noupdate /CPU_toplevel_tb/dut/MemRead
add wave -noupdate /CPU_toplevel_tb/dut/ALUOp
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2466182008 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {5407500 ns}
